#pragma once

#undef RGBLIGHT_EFFECT_BREATHING
#undef RGBLIGHT_EFFECT_STATIC_GRADIENT
#undef RGBLIGHT_EFFECT_RAINBOW_MOOD
#undef RGBLIGHT_EFFECT_RAINBOW_SWIRL
#undef RGBLIGHT_EFFECT_SNAKE
#undef RGBLIGHT_EFFECT_KNIGHT
#undef RGBLIGHT_EFFECT_CHRISTMAS
#undef RGBLIGHT_EFFECT_RGB_TEST
#undef RGBLIGHT_EFFECT_ALTERNATING
#undef RGBLIGHT_EFFECT_TWINKLE


#define RGBLIGHT_LAYERS_OVERRIDE_RGB_OFF

#define RGBLIGHT_LAYERS
#define DYNAMIC_KEYMAP_LAYER_COUNT 3

#define HOLD_ON_OTHER_KEY_PRESS

#define SPLIT_LAYER_STATE_ENABLE
#define SPLIT_LED_STATE_ENABLE
#define SPLIT_MODS_ENABLE
